### ISSUE TITLE
hostapd Execution error

### ISSUE THREAD

**Issue by INKYUSONGG** [tuomaura/eap-noob#5]
It's done in sequence, but it doesn't work. 
error : RADIUS SRV: Invalid line 1 in 'hostapd.radius_clients' 
There is an error in this part.

**Comment by ms-s** [comment]
hostapd.radius_client contains configuration information about the RADIUS clients. Depending on your deployment, the RADIUS client may reside in the access point (NAS). An example configuration line will be as follows: 

10.1.2.3	secret_passphrase

Here, 10.1.2.3 is the IP address of your access point and secret_passphrase is the secret used for securing the RADIUS packets. You will need to replace the current contents of the file, replacing the NASIP with the actual IP address of your RADIUS client and shared-secret-with-nas with the secret that is configured on the RADIUS client.

**Comment by INKYUSONGG** [comment]
Thank you for your answers.

And I have a question in the DB section.

The 'peers_connected' table is not visible in the database. So I want to know where I create.
